services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./conf:/usr/src/app/conf
      - ./data:/usr/src/app/data
      - /Users/amiantos/Coding/thelounge/data/logs/amiantos/libera.chat-e-418e-bb47-49c542e99479:/usr/src/app/irc-logs:ro
    environment:
      - NODE_ENV=production
    command: npm start
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
